version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: "prisma_db"
      POSTGRES_SCHEMA: "public"
      POSTGRES_SSL: "false"
      POSTGRES_POOL_SIZE: "20"
    network_mode: host
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: